mongodb fetch
CodeSpace-Academy/ASE_2023_GROUP_B pull request #42
Opened 2023-10-10 14:22 UTC by HermanNgwenya

Fetched data from Mongodb

2023-10-11 07:14 UTC, joshuawiidrichter1994 approved these changes

2023-10-11 07:48 UTC, joshuawiidrichter1994 submitted a review, later dismissed

2023-10-11 08:58 UTC, Renzo-codespace requested changes
- give the function a more descriptive name, e.g. fetchRecipes
- instanstiate the client outside of the function, i.e. every function that interacts with the db has access to the same instance of the client
- connection strings are sensitive data, should never be committed, needs to be moved to the .env file, which should be included in the gitignore
- at the end of the function, run client.close()

2023-10-12 08:03 UTC, joshuawiidrichter1994 commented
> * give the function a more descriptive name, e.g. fetchRecipes
> * instanstiate the client outside of the function, i.e. every function that interacts with the db has access to the same instance of the client
> * connection strings are sensitive data, should never be committed, needs to be moved to the .env file, which should be included in the gitignore

Hi Renzo,

The team made these changes. If you are happy with the changes, can we get permission to merge? 

Thanks.

2023-10-12 08:05 UTC, joshuawiidrichter1994 approved these changes

2023-10-12 14:22 UTC, Renzo-codespace approved these changes
Good work! Appreciate it.

2023-10-12 15:01 UTC, merged